/**
 *
 * $Id$
 */
package IFML.Core.validation;

import IFML.Core.Context;

import IFML.DataTypes.ContextVariableScope;

/**
 * A sample validator interface for {@link IFML.Core.ContextVariable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContextVariableValidator {
	boolean validate();

	boolean validateContext(Context value);
	boolean validateScope(ContextVariableScope value);
}
