/**
 *
 * $Id$
 */
package IFML.Core.validation;

import IFML.Core.BehaviorConcept;
import IFML.Core.BehavioralFeatureConcept;

/**
 * A sample validator interface for {@link IFML.Core.DynamicBehavior}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DynamicBehaviorValidator {
	boolean validate();

	boolean validateBehavioralFeatureConcept(BehavioralFeatureConcept value);
	boolean validateBehaviorConcept(BehaviorConcept value);
}
