/**
 *
 * $Id$
 */
package IFML.Core.validation;

import IFML.Core.ActivationExpression;
import IFML.Core.InteractionFlowExpression;

/**
 * A sample validator interface for {@link IFML.Core.Event}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EventValidator {
	boolean validate();

	boolean validateActivationExpression(ActivationExpression value);
	boolean validateInteractionFlowExpression(InteractionFlowExpression value);
}
