/**
 *
 * $Id$
 */
package IFML.Core.validation;

import IFML.Core.DynamicBehavior;
import IFML.Core.ViewContainer;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link IFML.Core.IFMLAction}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IFMLActionValidator {
	boolean validate();

	boolean validateActionEvents(EList value);
	boolean validateDynamicBehavior(DynamicBehavior value);
	boolean validateViewContainer(ViewContainer value);
}
