/**
 *
 * $Id$
 */
package IFML.Core.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link IFML.Core.ViewContainer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ViewContainerValidator {
	boolean validate();

	boolean validateIsLandmark(boolean value);
	boolean validateIsDefault(boolean value);
	boolean validateIsXOR(boolean value);
	boolean validateViewElements(EList value);
	boolean validateActions(EList value);
}
